COUNTRY_LANG_MAP = {
    'RU': {'lang': 'ru-RU', 'browser_lang': 'ru'},
    'UA': {'lang': 'uk-UA', 'browser_lang': 'uk'},
    'BY': {'lang': 'be-BY', 'browser_lang': 'be'},
    'US': {'lang': 'en-US', 'browser_lang': 'en'},
    'GB': {'lang': 'en-GB', 'browser_lang': 'en'},
    'DE': {'lang': 'de-DE', 'browser_lang': 'de'},
    'FR': {'lang': 'fr-FR', 'browser_lang': 'fr'},
    'IT': {'lang': 'it-IT', 'browser_lang': 'it'},
    'ES': {'lang': 'es-ES', 'browser_lang': 'es'},
    'PT': {'lang': 'pt-PT', 'browser_lang': 'pt'},
    'PL': {'lang': 'pl-PL', 'browser_lang': 'pl'},
    'RO': {'lang': 'ro-RO', 'browser_lang': 'ro'},
    'NL': {'lang': 'nl-NL', 'browser_lang': 'nl'},
    'HU': {'lang': 'hu-HU', 'browser_lang': 'hu'},
    'TR': {'lang': 'tr-TR', 'browser_lang': 'tr'},
    'JP': {'lang': 'ja-JP', 'browser_lang': 'ja'},
    'CN': {'lang': 'zh-CN', 'browser_lang': 'zh'},
    'KR': {'lang': 'ko-KR', 'browser_lang': 'ko'},
    
    'AT': {'lang': 'de-AT', 'browser_lang': 'de'},
    'CH': {'lang': 'de-CH', 'browser_lang': 'de'},
    'BE': {'lang': 'nl-BE', 'browser_lang': 'nl'},
    'DK': {'lang': 'da-DK', 'browser_lang': 'da'},
    'FI': {'lang': 'fi-FI', 'browser_lang': 'fi'},
    'NO': {'lang': 'nb-NO', 'browser_lang': 'nb'},
    'SE': {'lang': 'sv-SE', 'browser_lang': 'sv'},
    'IE': {'lang': 'en-IE', 'browser_lang': 'en'},
    'CZ': {'lang': 'cs-CZ', 'browser_lang': 'cs'},
    'SK': {'lang': 'sk-SK', 'browser_lang': 'sk'},
    'HR': {'lang': 'hr-HR', 'browser_lang': 'hr'},
    'SI': {'lang': 'sl-SI', 'browser_lang': 'sl'},
    'BG': {'lang': 'bg-BG', 'browser_lang': 'bg'},
    'GR': {'lang': 'el-GR', 'browser_lang': 'el'},
    'EE': {'lang': 'et-EE', 'browser_lang': 'et'},
    'LV': {'lang': 'lv-LV', 'browser_lang': 'lv'},
    'LT': {'lang': 'lt-LT', 'browser_lang': 'lt'},
    
    'TW': {'lang': 'zh-TW', 'browser_lang': 'zh'},
    'HK': {'lang': 'zh-HK', 'browser_lang': 'zh'},
    'SG': {'lang': 'en-SG', 'browser_lang': 'en'},
    'MY': {'lang': 'ms-MY', 'browser_lang': 'ms'},
    'TH': {'lang': 'th-TH', 'browser_lang': 'th'},
    'VN': {'lang': 'vi-VN', 'browser_lang': 'vi'},
    'ID': {'lang': 'id-ID', 'browser_lang': 'id'},
    'IN': {'lang': 'hi-IN', 'browser_lang': 'hi'},
    'PK': {'lang': 'ur-PK', 'browser_lang': 'ur'},
    
    'IL': {'lang': 'he-IL', 'browser_lang': 'he'},
    'SA': {'lang': 'ar-SA', 'browser_lang': 'ar'},
    'AE': {'lang': 'ar-AE', 'browser_lang': 'ar'},
    'EG': {'lang': 'ar-EG', 'browser_lang': 'ar'},
    
    'CA': {'lang': 'en-CA', 'browser_lang': 'en'},
    'MX': {'lang': 'es-MX', 'browser_lang': 'es'},
    'BR': {'lang': 'pt-BR', 'browser_lang': 'pt'},
    'AR': {'lang': 'es-AR', 'browser_lang': 'es'},
    'CL': {'lang': 'es-CL', 'browser_lang': 'es'},
    'CO': {'lang': 'es-CO', 'browser_lang': 'es'},
    
    'AU': {'lang': 'en-AU', 'browser_lang': 'en'},
    'NZ': {'lang': 'en-NZ', 'browser_lang': 'en'},
}

